"""Render validated ReproIR into deterministic synchronous Playwright code."""

from __future__ import annotations

import re

from repro.schemas import Action, LocatorSpec, Oracle, ReproIR


def render_locator(locator: LocatorSpec) -> str:
    base = render_locator(locator.scope) if locator.scope else "page"

    if locator.strategy == "role":
        arguments = [repr(locator.role)]
        if locator.name is not None:
            arguments.append(f"name={locator.name!r}")
        arguments.append(f"exact={locator.exact!r}")
        rendered = f"{base}.get_by_role({', '.join(arguments)})"
    elif locator.strategy == "label":
        rendered = f"{base}.get_by_label({locator.value!r}, exact={locator.exact!r})"
    elif locator.strategy == "test_id":
        rendered = f"{base}.get_by_test_id({locator.value!r})"
    elif locator.strategy == "text":
        rendered = f"{base}.get_by_text({locator.value!r}, exact={locator.exact!r})"
    else:  # pragma: no cover - Pydantic prevents this branch.
        raise ValueError(f"Unsupported locator strategy: {locator.strategy}")

    if locator.has_text is not None:
        rendered += f".filter(has_text={locator.has_text!r})"
    return rendered


def render_action(action: Action) -> str:
    if action.kind == "click":
        return f"{render_locator(action.target)}.click()"
    if action.kind == "fill":
        return f"{render_locator(action.target)}.fill({action.value!r})"
    if action.kind == "press":
        return f"{render_locator(action.target)}.press({action.key!r})"
    if action.kind == "select":
        return f"{render_locator(action.target)}.select_option({action.value!r})"
    if action.kind == "scroll":
        return f"page.mouse.wheel({action.delta_x}, {action.delta_y})"
    raise ValueError(f"Unsupported action kind: {action.kind}")


def render_oracle(oracle: Oracle) -> str:
    if oracle.kind == "url":
        return f"expect(page).to_have_url({oracle.expected_value!r})"

    target = render_locator(oracle.target)
    if oracle.kind == "visible":
        return f"expect({target}).to_be_visible()"
    if oracle.kind == "hidden":
        return f"expect({target}).to_be_hidden()"
    if oracle.kind == "value":
        return f"expect({target}).to_have_value({oracle.expected_value!r})"
    if oracle.kind == "text":
        method = "to_have_text" if oracle.match == "exact" else "to_contain_text"
        return f"expect({target}).{method}({oracle.expected_value!r})"
    raise ValueError(f"Unsupported oracle kind: {oracle.kind}")


def render_test(ir: ReproIR, test_name: str = "test_reproduced_bug") -> str:
    if not re.fullmatch(r"test_[A-Za-z0-9_]+", test_name):
        raise ValueError("test_name must be a valid pytest test identifier")

    body = [
        "mark_phase('setup', 'navigate')",
        f"page.set_viewport_size({ir.viewport.model_dump()!r})",
        f"page.goto({str(ir.start_url)!r}, wait_until='domcontentloaded')",
    ]
    for index, action in enumerate(ir.setup_actions, start=1):
        body.append(f"mark_phase('setup', 'setup-{index:03d}')")
        body.append(render_action(action))
    for index, action in enumerate(ir.actions, start=1):
        body.append(f"mark_phase('action', 'action-{index:03d}')")
        body.append(render_action(action))
    body.append("mark_phase('oracle', 'oracle')")
    body.append(render_oracle(ir.oracle))
    body.append("mark_phase('passed')")

    indented_body = "\n".join(f"    {line}" for line in body)
    return (
        "# Generated by repro. Do not edit by hand.\n"
        "from playwright.sync_api import Page, expect\n\n\n"
        "from repro.runtime import mark_phase\n\n\n"
        f"def {test_name}(page: Page) -> None:\n"
        f"{indented_body}\n"
    )

